springdoc:
  api-docs:
    enabled: true # 开启OpenApi接口
    path: /user-service
  swagger-ui:
    enabled: true # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启
    path: /swagger-ui/index.html   # 自定义路径，默认为"/swagger-ui/index.html"
server:
  port: 8090
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
  type-aliases-package: com.first_week.demo.Entity

spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/soft?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    type: com.zaxxer.hikari.HikariDataSource

